%% Suggested Name: plot_binning_robustness_comparison.m
% Compares Topologies generated by K=20 (Baseline) vs K=10 and K=5.
% Evaluates consistency across Raw, Node, and Network aggregations.

clc; clear; close all;

%% 1. Configuration & Paths
project_root = 'F:\PhD Code\My_PhD_Project';
session = 'REST1_LR';
clean_pipe = 'No_clean\';

% Base Directories
dir_base_20 = fullfile(project_root, 'results', 'Modulated_FC');
dir_base_rob = fullfile(project_root, 'results', 'Modulated_FC_Robustness');

% Load Atlas Info
atlas_info_path = fullfile(project_root, 'data', 'atlases', 'Schaefer2018_200Parcels_Kong2022_17Networks_order_info.txt');
addpath(genpath(fullfile(project_root, 'src', '04_utility')));
[~, roi_nets] = load_atlas_info(atlas_info_path);
unique_nets = unique(roi_nets, 'stable'); 
n_nets = 17; n_rois = 200;
[u_map, v_map] = find(triu(true(n_rois), 1));
net_idx_map = zeros(n_rois, 1);
for i=1:n_rois, net_idx_map(i) = find(strcmp(unique_nets, roi_nets{i})); end

%% 2. Function to Extract and Correlate Data
% We will compare [20 vs 10] and [20 vs 5]
comparisons = {10, 5};
metrics = {'variance', 'slope', 'zcr', 'best_poly_degree'};
n_mets = length(metrics);

% Storage: [Subject vs Group] x [Metrics] x [Levels: Raw, Node, Net] x [2 Comparisons]
Corr_Subj = zeros(n_mets, 3, 2); 
Corr_Grp  = zeros(n_mets, 3, 2);

% --- Load Group-Level Data for Baseline K=20 ---
G20_dir = fullfile(dir_base_20, 'Group_Level', session);
G20_v = load(fullfile(G20_dir, 'Group_Variance_Consensus.mat'));
G20_t = load(fullfile(G20_dir, 'Group_Slope_Tmap.mat'));
G20_z = load(fullfile(G20_dir, 'Group_ZCR_Median.mat'));
G20_p = load(fullfile(G20_dir, 'Group_Poly_Prevalence.mat'));

G20_Raw = {G20_v.Consensus_Percent, G20_t.T_map, G20_z.Median, double(G20_p.Mode)};

% Process for both K=10 and K=5
for comp_idx = 1:2
    k_target = comparisons{comp_idx};
    fprintf('Comparing K=20 vs K=%d...\n', k_target);
    
    dir_target = fullfile(dir_base_rob, sprintf('Bins_%d', k_target));
    
    % A. GROUP LEVEL COMPARISON
    G_tgt_dir = fullfile(dir_target, 'Group_Level', session);
    Gt_v = load(fullfile(G_tgt_dir, 'Group_Variance_Consensus.mat'));
    Gt_t = load(fullfile(G_tgt_dir, 'Group_Slope_Tmap.mat'));
    Gt_z = load(fullfile(G_tgt_dir, 'Group_ZCR_Median.mat'));
    Gt_p = load(fullfile(G_tgt_dir, 'Group_Poly_Prevalence.mat'));
    
    Gt_Raw = {Gt_v.Consensus_Percent, Gt_t.T_map, Gt_z.Median, double(Gt_p.Mode)};
    
    for m = 1:4
        % 1. Raw Level Group
        idx = ~isnan(G20_Raw{m}(:)) & ~isnan(Gt_Raw{m}(:)) & (G20_Raw{m}(:) ~= 255);
        Corr_Grp(m, 1, comp_idx) = corr(G20_Raw{m}(idx), Gt_Raw{m}(idx));
        
        % 2. Node Level Group (Mean across edges)
        n20 = std(G20_Raw{m}, 0, 1, 'omitnan')'; % For Variance, adapt logic for others if needed
        ntgt = std(Gt_Raw{m}, 0, 1, 'omitnan')';
        if m==2 % Slope uses Absolute Mean
            n20 = mean(abs(G20_Raw{m}), 1, 'omitnan')'; ntgt = mean(abs(Gt_Raw{m}), 1, 'omitnan')';
        elseif m==3 || m==4 % ZCR and Poly use Mean
            n20 = mean(G20_Raw{m}, 1, 'omitnan')'; ntgt = mean(Gt_Raw{m}, 1, 'omitnan')';
        end
        idx_n = ~isnan(n20) & ~isnan(ntgt);
        Corr_Grp(m, 2, comp_idx) = corr(n20(idx_n), ntgt(idx_n));
        
        % 3. Network Level Group
        net20  = map_edges_to_network(mean(G20_Raw{m}, 2, 'omitnan'), u_map, v_map, net_idx_map, n_nets);
        net_tgt = map_edges_to_network(mean(Gt_Raw{m}, 2, 'omitnan'), u_map, v_map, net_idx_map, n_nets);
        idx_net = ~isnan(net20(:)) & ~isnan(net_tgt(:));
        Corr_Grp(m, 3, comp_idx) = corr(net20(idx_net), net_tgt(idx_net));
    end
    
    % B. SUBJECT LEVEL COMPARISON (Averaged across 100 subjects)
    % (We can sample just 20 subjects to save massive time, as it's enough for a robustness check)
    files20 = dir(fullfile(dir_base_20, session, clean_pipe, '*_dyn_mod.mat'));
    n_sample = min(100, length(files20)); 
    
    sub_corr = zeros(n_sample, 4, 3); % [Subs x Metrics x Levels]
    
    for i = 1:n_sample
        % Load K=20
        R20 = load(fullfile(files20(i).folder, files20(i).name));
        % Load K=target
        tgt_name = strrep(files20(i).name, '_dyn_mod.mat', sprintf('_dyn_mod_b%d.mat', k_target));
        Rtgt = load(fullfile(dir_target, session, clean_pipe, tgt_name));
        
        r20_cell = {R20.variance, R20.slope, R20.zcr, double(R20.best_poly_degree)};
        rtgt_cell = {Rtgt.variance, Rtgt.slope, Rtgt.zcr, double(Rtgt.best_poly_degree)};
        
        for m = 1:4
            % Raw
            idx = ~isnan(r20_cell{m}(:)) & ~isnan(rtgt_cell{m}(:)) & (r20_cell{m}(:) ~= 255);
            sub_corr(i, m, 1) = corr(r20_cell{m}(idx), rtgt_cell{m}(idx));
            
            % Node
            if m==1, n20=std(r20_cell{m},0,1,'omitnan')'; ntgt=std(rtgt_cell{m},0,1,'omitnan')';
            elseif m==2, n20=mean(abs(r20_cell{m}),1,'omitnan')'; ntgt=mean(abs(rtgt_cell{m}),1,'omitnan')';
            else, n20=mean(r20_cell{m},1,'omitnan')'; ntgt=mean(rtgt_cell{m},1,'omitnan')'; end
            sub_corr(i, m, 2) = corr(n20, ntgt, 'Rows', 'complete');
            
            % Network
            net20  = map_edges_to_network(mean(r20_cell{m}, 2, 'omitnan'), u_map, v_map, net_idx_map, n_nets);
            net_tgt = map_edges_to_network(mean(rtgt_cell{m}, 2, 'omitnan'), u_map, v_map, net_idx_map, n_nets);
            sub_corr(i, m, 3) = corr(net20(:), net_tgt(:), 'Rows', 'complete');
        end
    end
    
    % Average subject correlations
    Corr_Subj(:, :, comp_idx) = squeeze(mean(sub_corr, 1, 'omitnan'));
end

%% 3. Visualization (Bar Charts)
fig = figure('Color', 'w', 'Position', [100, 100, 1200, 800], 'Name', 'Binning Robustness Group');
sgtitle('Robustness of Modulatory Topologies to the Number of Amplitude Bins in Group Level', 'FontSize', 16, 'FontWeight', 'bold');

metric_titles = {'Variance', 'Slope', 'ZCR', 'Polynomial Degree'};
levels = {'Raw Edge', 'Node-Level', 'Network-Level'};
colors = [0.2 0.6 0.8; 0.9 0.5 0.1]; % Blue for K=10, Orange for K=5

for m = 1:4
    subplot(2, 2, m);
    
    % We will plot Group-Level robustness (can switch to Subject-Level if you prefer)
    % Format for bar chart: [3 Levels x 2 Comparisons]
    data_to_plot = squeeze(Corr_Grp(m, :, :)); 
    
    b = bar(data_to_plot, 'grouped', 'EdgeColor', 'k');
    b(1).FaceColor = colors(1,:); b(2).FaceColor = colors(2,:);
    
    hold on;
    % Add text labels
    for col = 1:2
        x_pos = b(col).XData;
        y_val = b(col).YData;
        for j = 1:3
            text(x_pos(j), y_val(j) + 0.05, sprintf('%.2f', y_val(j)), ...
                'HorizontalAlignment', 'center', 'FontSize', 10, 'FontWeight', 'bold');
        end
    end
    
    title(metric_titles{m}, 'FontSize', 14);
    ylabel('Pearson r (vs. Baseline K=20)');
    ylim([0 1.15]);
    xticks(1:3); xticklabels(levels);
    set(gca, 'TickDir', 'out', 'Box', 'off');
    grid on;
    
    if m == 1
        legend({'K=20 vs K=10 (120 TRs/Bin)', 'K=20 vs K=5 (240 TRs/Bin)'}, 'Location', 'SouthWest');
    end
end

fig2 = figure('Color', 'w', 'Position', [100, 100, 1200, 800], 'Name', 'Binning Robustness Subject');
sgtitle('Robustness of Modulatory Topologies to the Number of Amplitude Bins in Subject level', 'FontSize', 16, 'FontWeight', 'bold');

for m = 1:4
    subplot(2, 2, m);
    
    % We will plot Subject-Level robustness (can switch to Subject-Level if you prefer)
    % Format for bar chart: [3 Levels x 2 Comparisons]
    data_to_plot = squeeze(Corr_Subj(m, :, :)); 
    
    b = bar(data_to_plot, 'grouped', 'EdgeColor', 'k');
    b(1).FaceColor = colors(1,:); b(2).FaceColor = colors(2,:);
    
    hold on;
    % Add text labels
    for col = 1:2
        x_pos = b(col).XData;
        y_val = b(col).YData;
        for j = 1:3
            text(x_pos(j), y_val(j) + 0.05, sprintf('%.2f', y_val(j)), ...
                'HorizontalAlignment', 'center', 'FontSize', 10, 'FontWeight', 'bold');
        end
    end
    
    title(metric_titles{m}, 'FontSize', 14);
    ylabel('Pearson r (vs. Baseline K=20)');
    ylim([0 1.15]);
    xticks(1:3); xticklabels(levels);
    set(gca, 'TickDir', 'out', 'Box', 'off');
    grid on;
    
    if m == 1
        legend({'K=20 vs K=10 (120 TRs/Bin)', 'K=20 vs K=5 (240 TRs/Bin)'}, 'Location', 'SouthWest');
    end
end

%% --- HELPER FUNCTION ---
function net_mat = map_edges_to_network(edge_vec, u, v, net_idx_map, n_nets)
    sum_scores = zeros(n_nets, n_nets); count_scores = zeros(n_nets, n_nets);
    for e = 1:length(u)
        ni = u(e); nj = v(e);
        net_i = net_idx_map(ni); net_j = net_idx_map(nj);
        val = edge_vec(e);
        if ~isnan(val)
            sum_scores(net_i, net_j) = sum_scores(net_i, net_j) + val;
            count_scores(net_i, net_j) = count_scores(net_i, net_j) + 1;
            if net_i ~= net_j
                sum_scores(net_j, net_i) = sum_scores(net_j, net_i) + val;
                count_scores(net_j, net_i) = count_scores(net_j, net_i) + 1;
            end
        end
    end
    net_mat = sum_scores ./ count_scores;
end