%% Suggested Name: plot_binning_strategy_comparison.m
% Compares Topologies generated by Quantile (Baseline) vs Uniform vs Sliding Window.
% Evaluates consistency across Raw, Node, and Network aggregations at both Subject and Group levels.

clc; clear; close all;

%% 1. Configuration & Paths
project_root = 'F:\PhD Code\My_PhD_Project';
session = 'REST1_LR';
clean_pipe = 'No_clean\';

% Base Directories
dir_base_quant = fullfile(project_root, 'results', 'Modulated_FC'); % Baseline
dir_base_alts  = fullfile(project_root, 'results', 'Modulated_FC_Alternatives'); % Alternatives

% Load Atlas Info
atlas_info_path = fullfile(project_root, 'data', 'atlases', 'Schaefer2018_200Parcels_Kong2022_17Networks_order_info.txt');
addpath(genpath(fullfile(project_root, 'src', '04_utility')));
[~, roi_nets] = load_atlas_info(atlas_info_path);
unique_nets = unique(roi_nets, 'stable'); 
n_nets = 17; n_rois = 200;
[u_map, v_map] = find(triu(true(n_rois), 1));
net_idx_map = zeros(n_rois, 1);
for i=1:n_rois, net_idx_map(i) = find(strcmp(unique_nets, roi_nets{i})); end

%% 2. Function to Extract and Correlate Data
% Comparisons: 1=Uniform vs Quantile, 2=SlidingWindow vs Quantile
strategies = {'Uniform', 'SlidingWindow'};
metrics = {'variance', 'slope', 'zcr', 'best_poly_degree'};
n_mets = length(metrics);

% Storage: [Subject vs Group] x [Metrics] x [Levels: Raw, Node, Net] x [2 Strategies]
Corr_Subj = zeros(n_mets, 3, 2); 
Corr_Grp  = zeros(n_mets, 3, 2);

% --- Load Group-Level Data for Baseline (Quantile K=20) ---
G_quant_dir = fullfile(dir_base_quant, 'Group_Level', session);
GQ_v = load(fullfile(G_quant_dir, 'Group_Variance_Consensus.mat'));
GQ_t = load(fullfile(G_quant_dir, 'Group_Slope_Tmap.mat'));
GQ_z = load(fullfile(G_quant_dir, 'Group_ZCR_Median.mat'));
GQ_p = load(fullfile(G_quant_dir, 'Group_Poly_Prevalence.mat'));

GQ_Raw = {GQ_v.Consensus_Percent, GQ_t.T_map, GQ_z.Median, double(GQ_p.Mode)};

fprintf('Starting Comparison Analysis...\n');

% Process for both Uniform and SlidingWindow
for comp_idx = 1:2
    strategy_name = strategies{comp_idx};
    fprintf('Comparing Quantile (Baseline) vs %s...\n', strategy_name);
    
    dir_target = fullfile(dir_base_alts, sprintf('Strategy_%s', strategy_name));
    
    % =======================================================
    % A. GROUP LEVEL COMPARISON
    % =======================================================
    G_tgt_dir = fullfile(dir_target, 'Group_Level', session);
    Gt_v = load(fullfile(G_tgt_dir, 'Group_Variance_Consensus.mat'));
    Gt_t = load(fullfile(G_tgt_dir, 'Group_Slope_Tmap.mat'));
    Gt_z = load(fullfile(G_tgt_dir, 'Group_ZCR_Median.mat'));
    Gt_p = load(fullfile(G_tgt_dir, 'Group_Poly_Prevalence.mat'));
    
    Gt_Raw = {Gt_v.Consensus_Percent, Gt_t.T_map, Gt_z.Median, double(Gt_p.Mode)};
    
    for m = 1:4
        % 1. Raw Level Group
        idx = ~isnan(GQ_Raw{m}(:)) & ~isnan(Gt_Raw{m}(:)) & (GQ_Raw{m}(:) ~= 255);
        Corr_Grp(m, 1, comp_idx) = corr(GQ_Raw{m}(idx), Gt_Raw{m}(idx), 'Rows', 'complete');
        
        % 2. Node Level Group (Mean across edges)
        nq = std(GQ_Raw{m}, 0, 1, 'omitnan')'; ntgt = std(Gt_Raw{m}, 0, 1, 'omitnan')';
        if m==2 % Slope uses Absolute Mean
            nq = mean(abs(GQ_Raw{m}), 1, 'omitnan')'; ntgt = mean(abs(Gt_Raw{m}), 1, 'omitnan')';
        elseif m==3 || m==4 % ZCR and Poly use Mean
            nq = mean(GQ_Raw{m}, 1, 'omitnan')'; ntgt = mean(Gt_Raw{m}, 1, 'omitnan')';
        end
        idx_n = ~isnan(nq) & ~isnan(ntgt);
        Corr_Grp(m, 2, comp_idx) = corr(nq(idx_n), ntgt(idx_n), 'Rows', 'complete');
        
        % 3. Network Level Group
        net_q  = map_edges_to_network(mean(GQ_Raw{m}, 2, 'omitnan'), u_map, v_map, net_idx_map, n_nets);
        net_tgt = map_edges_to_network(mean(Gt_Raw{m}, 2, 'omitnan'), u_map, v_map, net_idx_map, n_nets);
        idx_net = ~isnan(net_q(:)) & ~isnan(net_tgt(:));
        Corr_Grp(m, 3, comp_idx) = corr(net_q(idx_net), net_tgt(idx_net), 'Rows', 'complete');
    end
    
    % =======================================================
    % B. SUBJECT LEVEL COMPARISON (Averaged across subjects)
    % =======================================================
    % We use a representative sample of 20 subjects to save time, 
    % which is statistically sufficient for a methodological robustness check.
    files_q = dir(fullfile(dir_base_quant, session, clean_pipe, '*_dyn_mod.mat'));
    n_sample = min(100, length(files_q)); 
    
    sub_corr = zeros(n_sample, 4, 3); % [Subs x Metrics x Levels]
    
    for i = 1:n_sample
        % Load Quantile (Baseline)
        RQ = load(fullfile(files_q(i).folder, files_q(i).name));
        % Load Alternative Strategy
        tgt_name = strrep(files_q(i).name, '_dyn_mod.mat', sprintf('_dyn_mod_%s.mat', strategy_name));
        Rtgt = load(fullfile(dir_target, session, clean_pipe, tgt_name));
        
        rq_cell = {RQ.variance, RQ.slope, RQ.zcr, double(RQ.best_poly_degree)};
        rtgt_cell = {Rtgt.variance, Rtgt.slope, Rtgt.zcr, double(Rtgt.best_poly_degree)};
        
        for m = 1:4
            % 1. Raw Subject
            idx = ~isnan(rq_cell{m}(:)) & ~isnan(rtgt_cell{m}(:)) & (rq_cell{m}(:) ~= 255);
            sub_corr(i, m, 1) = corr(rq_cell{m}(idx), rtgt_cell{m}(idx), 'Rows', 'complete');
            
            % 2. Node Subject
            if m==1, nq=std(rq_cell{m},0,1,'omitnan')'; ntgt=std(rtgt_cell{m},0,1,'omitnan')';
            elseif m==2, nq=mean(abs(rq_cell{m}),1,'omitnan')'; ntgt=mean(abs(rtgt_cell{m}),1,'omitnan')';
            else, nq=mean(rq_cell{m},1,'omitnan')'; ntgt=mean(rtgt_cell{m},1,'omitnan')'; end
            sub_corr(i, m, 2) = corr(nq, ntgt, 'Rows', 'complete');
            
            % 3. Network Subject
            net_q  = map_edges_to_network(mean(rq_cell{m}, 2, 'omitnan'), u_map, v_map, net_idx_map, n_nets);
            net_tgt = map_edges_to_network(mean(rtgt_cell{m}, 2, 'omitnan'), u_map, v_map, net_idx_map, n_nets);
            sub_corr(i, m, 3) = corr(net_q(:), net_tgt(:), 'Rows', 'complete');
        end
    end
    
    % Average subject correlations
    Corr_Subj(:, :, comp_idx) = squeeze(mean(sub_corr, 1, 'omitnan'));
end

%% 3. Visualization (Bar Charts)
plot_comparison_chart(Corr_Grp, 'Group-Level Robustness to Binning Strategies', metrics, strategies);
plot_comparison_chart(Corr_Subj, 'Subject-Level Robustness to Binning Strategies', metrics, strategies);

%% --- HELPER FUNCTIONS ---
function plot_comparison_chart(Corr_Data, tit, metrics, strategies)
    fig = figure('Color', 'w', 'Position', [100, 100, 1200, 800], 'Name', tit);
    sgtitle(tit, 'FontSize', 16, 'FontWeight', 'bold');

    metric_titles = {'Variance', 'Slope', 'ZCR', 'Polynomial Degree'};
    levels = {'Raw Edge', 'Node-Level', 'Network-Level'};
    
    % Colors: Uniform (Purple), SlidingWindow (Teal)
    colors = [0.4940, 0.1840, 0.5560; 0.3010, 0.7450, 0.9330]; 

    for m = 1:4
        subplot(2, 2, m);
        
        % Data for this metric: [3 Levels x 2 Comparisons]
        data_to_plot = squeeze(Corr_Data(m, :, :)); 
        
        b = bar(data_to_plot, 'grouped', 'EdgeColor', 'k', 'LineWidth', 1);
        b(1).FaceColor = colors(1,:); 
        b(2).FaceColor = colors(2,:);
        
        hold on;
        % Add text labels on top of bars
        for col = 1:2
            x_pos = b(col).XData;
            y_val = b(col).YData;
            for j = 1:3
                text(x_pos(j), y_val(j) + 0.05, sprintf('%.2f', y_val(j)), ...
                    'HorizontalAlignment', 'center', 'FontSize', 10, 'FontWeight', 'bold');
            end
        end
        
        title(metric_titles{m}, 'FontSize', 14, 'FontWeight', 'bold');
        ylabel('Pearson r (vs. Original Quantile)');
        ylim([0 1.15]);
        xticks(1:3); xticklabels(levels);
        set(gca, 'TickDir', 'out', 'Box', 'off');
        grid on;
        
        if m == 1
            legend({'Uniform Amplitude', 'Sliding Window'}, 'Location', 'northwestoutside');
        end
    end
end

function net_mat = map_edges_to_network(edge_vec, u, v, net_idx_map, n_nets)
    sum_scores = zeros(n_nets, n_nets); count_scores = zeros(n_nets, n_nets);
    for e = 1:length(u)
        ni = u(e); nj = v(e);
        net_i = net_idx_map(ni); net_j = net_idx_map(nj);
        val = edge_vec(e);
        if ~isnan(val)
            sum_scores(net_i, net_j) = sum_scores(net_i, net_j) + val;
            count_scores(net_i, net_j) = count_scores(net_i, net_j) + 1;
            if net_i ~= net_j
                sum_scores(net_j, net_i) = sum_scores(net_j, net_i) + val;
                count_scores(net_j, net_i) = count_scores(net_j, net_i) + 1;
            end
        end
    end
    net_mat = sum_scores ./ count_scores;
end